project:
  type: website
  output-dir: docs

website:
  title: "Sociedad Científica de Estudiantes de Estadística"
  site-url: https://sociest.org
  favicon: images/logo.jpg
  description: ""
  bread-crumbs: true

  open-graph:
    locale: es_ES

  image: "images/logo.jpg"

  google-analytics: "G-ZEYEY0RVXJ"
  cookie-consent: true
  
  comments:
    giscus: 
      repo: sociest/sociest
      category: Q&A
      mapping: title
      reactions-enabled: true
      theme:
        light: light
        dark: dark_dimmed
      language: es

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Info** - Bienvenido a la pagina web de la sociedad! cualquier mejora pueden comentarlo!"
    type: primary
    position: below-navbar 

  repo-url: https://github.com/sociest/sociest
  repo-actions: [edit, source, issue]
  
  back-to-top-navigation: true
  
  navbar:
    pinned: true
    logo: "images/logo.jpg"
    logo-alt: SOCIEST
    left:
      - href: index.qmd
        text: Inicio
      - text: "Quiénes Somos"
        menu:
          - about\index.qmd
          - about\history.qmd
          - about\statute.qmd
      - text: "Nuestra Organización"
        menu:
          - organization\index.qmd
          - organization\members.qmd 
          - organization\cargos.qmd
      - text: "Proyectos"
        menu:
          - proyects\index.qmd
          - proyects\about.qmd
          - proyects\propurses.qmd
      - href: blog.qmd
        text: Blog
      - text: "Recursos"
        menu:
          - resources\media.qmd
      - href: contact.qmd
        text: Contacto
      - href: support.qmd
        text: Apoyo
    right:
      - icon: github
        href: https://github.com/sociest/
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029VaoHzI69xVJcZxVuiv05
      - icon: linkedin
        href: https://www.linkedin.com/company/sociest  
      - icon: facebook
        href: https://www.facebook.com/sociest
    tools:
      - icon: rss
        href: index.xml
      
  page-footer: 
    left: "Derechos Reservados 2024, Sociedad Científica de Estudiantes de Estadística" 
    right: 
      - icon: github
        href: https://github.com/sociest/
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029VaoHzI69xVJcZxVuiv05
      - icon: linkedin
        href: https://www.linkedin.com/company/sociest
      - icon: facebook
        href: https://www.facebook.com/sociest

server:
  https: true

format:
  html:
    lang: es
    css: styles.css
    theme:
      light: cosmo
      dark: darkly
    toc: true