project:
  type: website
  output-dir: _site

website:
  title: "Sociedad Científica de Estudiantes de Estadística"
  site-url: https://sociest.org
  description: ""

  comments:
    giscus: 
      repo: sociest/sociest.github.io
      category: Q&A
      mapping: title
      reactions-enabled: true
      theme:
        light: light
        dark: dark_dimmed
      language: es

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Info** - Bienvenido a la nueva pagina web de la sociedad!"
    type: primary
    position: below-navbar 

  repo-url: https://github.com/sociest/sociest.github.io
  repo-actions: [edit, source, issue]
  
  back-to-top-navigation: true
  
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: blog.qmd
        text: Blog
      - href: docs.qmd
        text: Documentación
      - href: about.qmd
        text: Sobre Nosotros
    right:
      - icon: rss
        href: index.xml
    tools:
      - icon: github
        href: https://github.com/sociest/
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029VaoHzI69xVJcZxVuiv05
      - icon: linkedin
        href: https://www.linkedin.com/company/sociest
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61566085296817
      
  page-footer: 
    left: "Copyright 2024, Sociedad Científica de Estudiantes de Estadística" 
    right: 
      - icon: github
        href: https://github.com/sociest/
      - icon: whatsapp
        href: https://whatsapp.com/channel/0029VaoHzI69xVJcZxVuiv05
      - icon: linkedin
        href: https://www.linkedin.com/company/sociest
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61566085296817
  
format:
  html:
    language: es
    css: styles.css
    theme:
      light: cosmo
      dark: darkly
    toc: true