---
title: Historia
toc: true
reader-mode: true
comments: false
---

# Antecedentes

La idea de formar una sociedad en una carrera tan viva y transversal como la estadística surgió del deseo colectivo de los estudiantes por crear un espacio donde se promoviera la investigación, el intercambio de conocimientos y el desarrollo de proyectos que respondieran a las necesidades de nuestra sociedad. La estadística, siendo una disciplina esencial para diversas áreas, desde la salud pública hasta la economía y las ciencias sociales, nos inspiró a organizarnos para fortalecer nuestra formación académica y contribuir de manera activa al desarrollo de soluciones a los problemas actuales. Conscientes de la importancia de esta ciencia, los estudiantes de la carrera de Estadística de la Universidad Mayor de San Andrés sentían la necesidad de formar un grupo que representara la investigación y la aplicación de la estadística a nivel académico y profesional.

# Proceso de Fundación

### 1. Inicios de la idea (1er y 2do Semestre de 2023)

Todo comenzó a inicios de 2023, cuando varios estudiantes discutieron por primera vez la posibilidad de crear una sociedad científica que reuniera a quienes compartían el entusiasmo por la estadística y la ciencia. Este fue un año en el que la relevancia de la estadística se hizo más evidente a nivel global y local, y esa motivación impulsó las primeras reuniones informales entre los estudiantes interesados.

### 2. Organización de los interesados (1er de 2024)

Durante los meses siguientes, un pequeño grupo de estudiantes comenzó a organizar encuentros y charlas sobre los beneficios de tener una sociedad científica con otros grupos de estudiantes dentro de la carrera. Fue en el segundo semestre de 2024 cuando se formó un comité provisorio para llevar a cabo la tarea de fundación, con el apoyo de docentes y autoridades que creían en la importancia de este proyecto.

### 3. Asamblea y consolidación (3 de octubre de 2024)

Finalmente, el 3 de octubre de 2024, se celebró una asamblea estudiantil en la ciudad de La Paz. En esa reunión histórica, los estudiantes de pregrado de la carrera de Estadística de la Facultad de Ciencias Puras y Naturales de la Universidad Mayor de San Andrés tomaron la decisión de consolidar formalmente la Sociedad Científica de Estudiantes de Estadística. La sociedad nace con la misión de promover la investigación académica, incentivar el desarrollo de habilidades prácticas y fomentar la colaboración entre estudiantes, docentes e instituciones externas.

# Fundación

Ese día, con gran entusiasmo y un firme sentido de propósito, los estudiantes presentarón el estatuto de la Sociedad Científica de Estudiantes de Estadística y sus reglamentos aparte de la firma del Acta de fundación. La asamblea marcó el inicio oficial de una etapa donde la estadística será el motor de cambio y avance para nuestra carrera y la sociedad en general.

[Enlace al Acta de fundación](https://docs.google.com/document/d/136bWXw5MJ4sGPyubL-V4UTUFXNtFR30JNGdlEhz3Mgc/edit?usp=drive_link)

# Mensaje al Futuro

Con la fundación de la Sociedad, aspiramos a construir un grupo sólido y dinámico que no solo promueva la investigación y el aprendizaje, sino que también contribuya de manera tangible al bienestar de nuestra sociedad. Sabemos que el camino por delante será desafiante, pero estamos comprometidos en trabajar unidos, aprender mutuamente y generar soluciones que impacten positivamente en Bolivia y el mundo. Nuestro sueño es convertirnos en una gran sociedad, capaz de marcar la diferencia, donde cada uno de nuestros miembros pueda desarrollarse plenamente, aportando su granito de arena para construir un mejor futuro.